version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://middleware:3001

  middleware:
    build:
      context: ./middleware
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./middleware:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - SDK_HOST=sdk
      - SDK_PORT=3002

  sdk:
    build:
      context: ./sdk
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - ./sdk:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

networks:
  default:
    name: agent-builder-network
