name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "staging", "feature/*" ]
  pull_request:
    branches: [ "main", "staging" ]
  workflow_dispatch:

permissions:
  contents: write
  security-events: write
  pull-requests: write
  issues: write
  deployments: write

jobs:
  analyze:
    name: Security Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: javascript
        queries: security-extended,security-and-quality

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:javascript"

  build:
    needs: analyze
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci --legacy-peer-deps

    - name: Run ESLint
      run: npm run lint || true

    - name: Build Application
      run: npm run build
      env:
        NODE_ENV: production

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: .next/
        retention-days: 7
        compression-level: 9

  deploy-staging:
    if: github.ref == 'refs/heads/staging'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: ${{ steps.deploy.outputs.url }}
    timeout-minutes: 10
    
    steps:
    - uses: actions/checkout@v4

    - name: Download Build Artifact
      uses: actions/download-artifact@v4
      with:
        name: build-output
        path: .next

    - name: Deploy to Vercel (Preview)
      id: deploy
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        github-comment: true
        vercel-args: '--force'

    - name: Comment Preview URL
      uses: actions/github-script@v7
      with:
        script: |
          const issue = context.issue;
          if (issue.number) {
            github.rest.issues.createComment({
              issue_number: issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🔍 Preview deployment completed!\nURL: ${process.env.DEPLOY_URL}\nBranch: staging`
            });
          }
      env:
        DEPLOY_URL: ${{ steps.deploy.outputs.url }}

  deploy-production:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ steps.deploy.outputs.url }}
    timeout-minutes: 10
    
    steps:
    - uses: actions/checkout@v4

    - name: Download Build Artifact
      uses: actions/download-artifact@v4
      with:
        name: build-output
        path: .next
    
    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        draft: false
        prerelease: false
        generate_release_notes: true

    - name: Deploy to Vercel (Production)
      id: deploy
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        vercel-args: '--prod'

    - name: Update Release with Deployment URL
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.repos.updateRelease({
            owner: context.repo.owner,
            repo: context.repo.repo,
            release_id: process.env.RELEASE_ID,
            body: `🚀 Production deployment completed!\nURL: ${process.env.DEPLOY_URL}\n\n${process.env.RELEASE_BODY}`
          });
      env:
        DEPLOY_URL: ${{ steps.deploy.outputs.url }}
        RELEASE_ID: ${{ steps.create_release.outputs.id }}
        RELEASE_BODY: ${{ steps.create_release.outputs.body }}
